name: 'Install Nix + RV Cachix'
inputs:
  github-token:
    description: 'Token for authenticating with GitHub'
    required: true
  cachix-key:
    description: 'Key for accessing Cachix'
    required: true
runs:
  using: 'composite'
  steps:
      - uses: cachix/install-nix-action@v15
        with:
          install_url: 'https://releases.nixos.org/nix/nix-2.3.16/install'
          extra_nix_config: |
            access-tokens = github.com=${{ inputs.github-token }}
            substituters = http://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@v10
        with:
          name: runtimeverification
          extraPullNames: kore
          signingKey: ${{ inputs.cachix-key }}
