name: 'Update Nix Flake Inputs'
on:
  push:
    branches:
      - '_update-deps_runtimeverification_haskell-backend'
      - '_update-deps_runtimeverification_llvm-backend'
  workflow_dispatch:
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  nix-flake-submodule-sync:
    name: 'Nix flake submodule sync'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code, set up Git'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          submodules: recursive
      - run: |
          git config --global user.name rv-jenkins
          git config --global user.email devops@runtimeverification.com

      - name: 'Set up Nix/Cachix'
        if: ${{ !startsWith(matrix.os, 'self') }}
        uses: ./.github/actions/install-nix-cachix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-key: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: 'Update Nix flake inputs from submodules'
        run: |
          GC_DONT_GC=1 nix run .#update-from-submodules
          if git add 'flake.lock' && git commit -m 'Sync flake inputs to submodules'; then
            git push
          fi
